### ISSUE TITLE
Admin - it logs me out after clicking on a module

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#876]
Unclear if I am the only one experiencing this.

Steps:

- login
- go to /admin
- click a module, such as Locations

Result: I get logged out, and sent to the login screen.

Then, after logging back in, everything works fine. This leads me to believe it's a cookie issue or something. But why would it not set the first time, but set the second?

@scottwainstock Can you replicate this?

**Comment by scottwainstock** [comment]
@RyanTG No. ssw account on live. Portland admin. Super admin.

**Comment by RyanTG** [comment]
OK. I'll close this. Must be a plugin fucking with things.

**Comment by RyanTG** [comment]
Re-opening. I can replicate this in Chrome, Chromium, Firefox (on windows and linux, with all plugins disabled), and Internet Explorer.
Using Super admin, regular admin, and Portland admin.

I can not replicate it on localhost using ssw, so I haven't been able to tail the log.

**Comment by RyanTG** [comment]
````
Request URL: https://www.pinballmap.com/admin/suggested_location?_pjax=[data-pjax-container]
Request method: OPTIONS
Remote address: 50.17.225.199:443
Status code: 404 Not Found

Request URL: https://www.pinballmap.com/admin/suggested_location
Request method: GET
Remote address: 50.17.225.199:443
Status code: 302 Found
```


So, the XHR request is failing - and I'm assuming it's producing a RoutingError because of invalid permissions. Why would it work the second time? Dunno.

**Comment by RyanTG** [comment]
Massive multi-year thread about this issue: https://github.com/plataformatec/devise/issues/2734

But, there are a number of possible solutions. One of which is "this isn't a devise issue" and "it's a browser setting issue." But most solutions are devise-oriented (even though it only affects some browsers).

**Comment by RyanTG** [comment]
For the record, other admins have complained about this issue.

**Comment by scottwainstock** [comment]
@RyanTG How about https://github.com/scottwainstock/pbm/commit/e1a818349d68953059373389cbe737ee6587baaf ? I was able to reproduce on live, but not after I pushed this code. It's a tricky one to reproduce though, so maybe I'm missing something.

**Comment by RyanTG** [comment]
I'm still getting logged out when I click a module (on live). I tried a couple browsers.

**Comment by scottwainstock** [comment]
Gem upgrade: https://github.com/scottwainstock/pbm/commit/345595014a8e60f32a68619504615ce4558fa004

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/391dfaf8d9949aa1e9eb9fa1ad3d4377263bcd1c
